# Cấu hình kết nối MySQL
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/auth_system?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=@Hoanghuyn98
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Cấu hình JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cấu hình Port chạy ứng dụng (Mặc định là 8080, bạn có thể đổi nếu muốn)
server.port=8080

spring.sql.init.mode=always